### ISSUE TITLE
Use Google Sheet to store the order and bento info

### ISSUE THREAD

**Issue by chochinlu** [chochinlu/ts-din-ben-ton#5]
使用 google sheet 來儲存訂單和菜單資料

這樣就可以多人使用

**Comment by ChuangYuMing** [comment]
目前改用firebase，這張可以關瞜
不過就要有辦法方便維護firestore上的資料了(人員跟菜單)

**Comment by chochinlu** [comment]
後續維護需要開issue,  目前人員和菜單都是寫死的 XDD
